#!/data/data/com.termux/files/usr/bin/bash
clear

echo "Please Input"
read -p "Domain :" domain
read -p "Host   : " host
data=./result/$domain/$domain

~/go/bin/bugscanner-go scan cdn-ssl --proxy-filename $data.bug --target $host -o $data.cdn

echo "========="
echo "Check $data.cdn for any result."