#!/data/data/com.termux/files/usr/bin/bash
clear

echo "Please Input"
read -p "Domain:" domain
data=./result/$domain/$domain

~/go/bin/bugscanner-go scan sni -f $data.lst --threads 16

echo ""
echo "========="
echo "Done!"